### ISSUE TITLE
Arango Client Not Instantiated

### ISSUE THREAD

**Issue by RainbowZephyr** [GoodforGod/micronaut-arangodb#28]
Hello,
I am running into a bit of trouble trying to get the library to work arango driver version 7.1+, it works fine with 7.0 but throws warning about unsupported Jackson since I am using SerdeFactory for Micronaut.

When I update to any version above 7.0 I get the following error:

```
Message: 'com.arangodb.internal.InternalArangoDBBuilder com.arangodb.ArangoDB$Builder.loadProperties(com.arangodb.config.ArangoConfigProperties)'
Path Taken: new $UserController$Definition$Intercepted(DatabaseContext databaseContext,BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry) --> new $UserController$Definition$Intercepted([DatabaseContext databaseContext],BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors,InterceptorRegistry $interceptorRegistry) --> new DatabaseContext([ArangoClient arangoClient]) --> ArangoClientFactory.getClient([ArangoDB accessor],ArangoConfiguration configuration)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2326)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2281)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2293)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3095)
	at io.micronaut.context.DefaultBeanContext$3.create(DefaultBeanContext.java:3073)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$getOrCreate$0(RefreshScope.java:87)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.getOrCreate(RefreshScope.java:86)
	at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:3056)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2982)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1470)
	at io.micronaut.configuration.arango.$ArangoAccessorFactory$GetAccessor0$Definition$Intercepted.interceptedTarget(Unknown Source)
	at io.micronaut.configuration.arango.$ArangoAccessorFactory$GetAccessor0$Definition$Intercepted.db(Unknown Source)
	at io.micronaut.configuration.arango.ArangoClientImpl.<init>(ArangoClientImpl.java:27)
	at io.micronaut.configuration.arango.ArangoClientFactory.getClient(ArangoClientFactory.java:23)
	at io.micronaut.configuration.arango.$ArangoClientFactory$GetClient0$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2311)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2281)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2293)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3095)
	at io.micronaut.context.DefaultBeanContext$3.create(DefaultBeanContext.java:3073)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$getOrCreate$0(RefreshScope.java:87)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.getOrCreate(RefreshScope.java:86)
	at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:3056)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2982)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1470)
	at io.micronaut.configuration.arango.$ArangoClientFactory$GetClient0$Definition$Intercepted.interceptedTarget(Unknown Source)
	at io.micronaut.configuration.arango.$ArangoClientFactory$GetClient0$Definition$Intercepted.db(Unknown Source)
	
Caused by: java.lang.NoSuchMethodError: 'com.arangodb.internal.InternalArangoDBBuilder com.arangodb.ArangoDB$Builder.loadProperties(com.arangodb.config.ArangoConfigProperties)'
	at io.micronaut.configuration.arango.ArangoAccessorFactory.createAccessor(ArangoAccessorFactory.java:59)
	at io.micronaut.configuration.arango.ArangoAccessorFactory.getAccessor(ArangoAccessorFactory.java:31)
	at io.micronaut.configuration.arango.$ArangoAccessorFactory$GetAccessor0$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2311)
	... 30 more
```

Database context is a class I have created to hold the database clients in this case. 

Any ideas as to what the issue would be?

**Comment by GoodforGod** [comment]
Will look into it
